import "./globals.scss";

import localFont from "@next/font/local";

const CaskaydiaCoveNFRegular = localFont({
  src: "../public/fonts/CaskaydiaCoveNF-Regular.woff2",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={CaskaydiaCoveNFRegular.className}>{children}</body>
    </html>
  );
}
